language: Lua
install:
  - pip install flake8 pep257
  - sudo apt-get update -qq
  - sudo apt-get install -y luarocks wget
  - sudo luarocks install luacheck

script:
  - luacheck . --no-global --no-self
